### ISSUE TITLE
GradientPalettes.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [NimmLor/esp8266-fastled-iot-webserver#10]
For one of my electronic projects, I use FastLED and Arduino WebSockets with a Wemos D1 mini, except that when I want to check or even upload it to my Wemos, the error given in the title is displayed. I use everything with their latest version.

**Comment by ghost** [comment]
Does anyone have any idea what this problem might be coming from? It's just that it's blocking me in the rest of the nanoleafs project.

**Comment by pattyland** [comment]
Did you use the correct version described in the readme?
