### ISSUE TITLE
music visualization in 4.4

### ISSUE THREAD

**Issue by dchwilk** [NimmLor/esp8266-fastled-iot-webserver#103]
The last update broke the music visualization

**Comment by bb-Ricardo** [comment]
@NimmLor What is broken there? Would I be able to fix it?

**Comment by NimmLor** [comment]
I don't know yet, I'll take a look tomorrow morning

**Comment by NimmLor** [comment]
Pretty stupid mistake, I've unintentionally removed the part in the setup() that starts the UDP server
