### ISSUE TITLE
How connect?

### ISSUE THREAD

**Issue by bsl-ender** [NimmLor/esp8266-fastled-iot-webserver#108]
Hi. Sorry for my bad and easy english.

How connect nodemcu to ws2812 ? 

Which pins in node connect to led strip and how?

I try connect NODE VIN to LED +5, NODE G to LED GND, NODE D3 to LED DO/Din...

Dont work :(

**Comment by bb-Ricardo** [comment]
Can you draw a little schematic? I don't really know how you connected all the parts.

**Comment by bb-Ricardo** [comment]
Closing this issue due to no response. If you still having troubles consider opening a new issue.
