### ISSUE TITLE
[Request] Auto brightness

### ISSUE THREAD

**Issue by cyber-junkie9** [NimmLor/esp8266-fastled-iot-webserver#113]
If possible can you please add support for LDR ?

**Comment by bb-Ricardo** [comment]
Hi,

Yes, this is possible. I just don't have any hardware to test and implement it. Sorry.

**Comment by bb-Ricardo** [comment]
Why don't you try to build it yourself?

I guess you would need to resd from an analog pin. And then set power or brightness depending on the value.

**Comment by bb-Ricardo** [comment]
closing due to no response.
