### ISSUE TITLE
4 Second Freezes

### ISSUE THREAD

**Issue by CrimsonAC** [NimmLor/esp8266-fastled-iot-webserver#114]
Hello and first of all, thanks for the great software and effort that's put into it.

I have a strange problem since the new 4.4 release.
The Wemos D1 Mini just seems to freeze for 4 seconds, then it works for 4 seconds, then it freezes again. 
This goes on and on, always in a approximately 4 seconds interval.
I didn't change anything in my setup between 4.3 and 4.4.

My setup:
12V Power Supply to BuckConverter -> 5V to Wemos D1 Mini.
12V Power Supply to W2811 LED-Stripe.
Wemos D1 Mini Data Pin to LED-Stripe.

I tried a second D1 Mini with the same result.
The web interface seems to lag during that phases, too.
For example, when switching between on and off, during those freeze times, the Stripe does not change and the web interface says "please wait" in the status line.

Going back to 4.3 and everything works again.

**Comment by scr1ptDev** [comment]
https://user-images.githubusercontent.com/62609951/103956530-026b9700-5149-11eb-9d37-6af981c49adb.mp4

Same problem. Start the program correctly, after a few seconds, it crashes. On different occasions, it crashes every 4 seconds, on other occasions it does not run the animations.
Indicate that it create an access point called "ESP-13E3F1" when in reality the hostname is "Ledlamp". The webserver is very, very slow.
When I mounted it yesterday, it worked perfect, it was to install IoT-Audio-Visualization-Center and stop working. I have flashed Wemos again, and nothing. Sorry english :)

**Comment by bb-Ricardo** [comment]
Can you add the serial output here? It looks like it is restarting in a loop. Are you using "Autoplay"?

**Comment by bb-Ricardo** [comment]
can you test the latest "in-development" branch and check the Serial Monitor?

**Comment by CrimsonAC** [comment]
Oh sorry, I didn't notice the reply in which you wanted to see the serial output.
I just tested the mentioned "in-development" branch. Everything seems to work fine. 
Here is a part of the serial output. I changed the patterns once or twice and did a reboot while the monitor was active (i blanked my wifi credentials).

14:33:39.086 -> DEBUG [42002]: Stats: 120 frames/s, frame delay: 7950 us
14:33:40.066 -> DEBUG [43004]: Stats: 120 frames/s, frame delay: 7950 us
14:33:41.084 -> DEBUG [44006]: Stats: 120 frames/s, frame delay: 7950 us
14:33:42.083 -> DEBUG [45007]: Stats: 120 frames/s, frame delay: 7950 us
14:33:43.071 -> DEBUG [46000]: Stats: 119 frames/s, frame delay: 7950 us
14:33:44.052 -> DEBUG [47000]: Stats: 120 frames/s, frame delay: 7950 us
14:33:45.071 -> DEBUG [48003]: Stats: 120 frames/s, frame delay: 7950 us
14:33:46.061 -> DEBUG [49005]: Stats: 120 frames/s, frame delay: 7950 us
14:33:47.083 -> DEBUG [50006]: Stats: 120 frames/s, frame delay: 7950 us
14:33:48.074 -> DEBUG [51000]: Stats: 119 frames/s, frame delay: 7950 us
14:33:49.059 -> DEBUG [52001]: Heap: 27536
14:33:49.059 -> DEBUG [52002]: Stats: 120 frames/s, frame delay: 7950 us
14:33:50.076 -> DEBUG [53004]: Stats: 120 frames/s, frame delay: 7950 us
14:33:50.244 -> DEBUG [53191]: Setting: pattern: Pride
14:33:51.088 -> DEBUG [54006]: Stats: 118 frames/s, frame delay: 7850 us
14:33:52.075 -> DEBUG [55003]: Stats: 121 frames/s, frame delay: 7850 us
14:33:53.061 -> DEBUG [56001]: Stats: 121 frames/s, frame delay: 7850 us
14:33:54.074 -> DEBUG [57004]: Stats: 122 frames/s, frame delay: 7950 us
14:33:55.090 -> DEBUG [58005]: Stats: 120 frames/s, frame delay: 7950 us
14:33:56.075 -> DEBUG [59004]: Stats: 120 frames/s, frame delay: 7950 us
14:33:57.060 -> DEBUG [60003]: Stats: 120 frames/s, frame delay: 7950 us
14:33:58.078 -> DEBUG [61005]: Stats: 120 frames/s, frame delay: 7950 us
14:33:59.083 -> DEBUG [62004]: Heap: 27368
14:33:59.083 -> DEBUG [62005]: Stats: 120 frames/s, frame delay: 7950 us
14:34:00.060 -> DEBUG [63005]: Stats: 120 frames/s, frame delay: 7950 us
14:34:00.265 -> DEBUG [63198]: Saving Config
14:34:00.467 -> DEBUG [63399]: Comitting config
14:34:01.076 -> DEBUG [64000]: Stats: 113 frames/s, frame delay: 7600 us
14:34:02.078 -> DEBUG [65005]: Stats: 126 frames/s, frame delay: 7900 us
14:34:03.069 -> DEBUG [66005]: Stats: 121 frames/s, frame delay: 7900 us
14:34:04.089 -> DEBUG [67006]: Stats: 121 frames/s, frame delay: 7900 us
14:34:05.074 -> DEBUG [68008]: Stats: 121 frames/s, frame delay: 7900 us
14:34:06.086 -> DEBUG [69003]: Stats: 120 frames/s, frame delay: 7900 us
14:34:07.076 -> DEBUG [70005]: Stats: 121 frames/s, frame delay: 7900 us
14:34:08.074 -> DEBUG [71007]: Stats: 121 frames/s, frame delay: 7900 us
14:34:09.062 -> DEBUG [72000]: Heap: 27368
14:34:09.062 -> DEBUG [72001]: Stats: 120 frames/s, frame delay: 7900 us
14:34:10.081 -> DEBUG [73002]: Stats: 121 frames/s, frame delay: 7900 us
14:34:11.061 -> DEBUG [74003]: Stats: 121 frames/s, frame delay: 7900 us
14:34:12.060 -> DEBUG [75005]: Stats: 121 frames/s, frame delay: 7900 us
14:34:13.077 -> DEBUG [76008]: Stats: 121 frames/s, frame delay: 7900 us
14:34:14.054 -> DEBUG [77000]: Stats: 120 frames/s, frame delay: 7900 us
14:34:15.083 -> DEBUG [78002]: Stats: 121 frames/s, frame delay: 7900 us
14:34:16.064 -> DEBUG [79003]: Stats: 121 frames/s, frame delay: 7900 us
14:34:17.073 -> DEBUG [80005]: Stats: 121 frames/s, frame delay: 7900 us
14:34:18.064 -> DEBUG [81008]: Stats: 121 frames/s, frame delay: 7900 us
14:34:19.075 -> DEBUG [82000]: Heap: 27368
14:34:19.075 -> DEBUG [82001]: Stats: 120 frames/s, frame delay: 7900 us
14:34:20.087 -> DEBUG [83002]: Stats: 121 frames/s, frame delay: 7900 us
14:34:21.066 -> DEBUG [84003]: Stats: 121 frames/s, frame delay: 7900 us
14:34:22.089 -> DEBUG [85004]: Stats: 121 frames/s, frame delay: 7900 us
14:34:23.072 -> DEBUG [86005]: Stats: 121 frames/s, frame delay: 7900 us
14:34:24.081 -> DEBUG [87005]: Stats: 121 frames/s, frame delay: 7900 us
14:34:25.067 -> DEBUG [88007]: Stats: 121 frames/s, frame delay: 7900 us
14:34:26.062 -> DEBUG [89004]: Stats: 110 frames/s, frame delay: 7400 us
14:34:27.056 -> DEBUG [90000]: Stats: 103 frames/s, frame delay: 6550 us
14:34:28.073 -> DEBUG [91003]: Stats: 145 frames/s, frame delay: 7800 us
14:34:29.062 -> DEBUG [92000]: Stats: 122 frames/s, frame delay: 7900 us
14:34:29.062 -> DEBUG [92008]: Heap: 27480
14:34:30.088 -> DEBUG [93005]: Stats: 100 frames/s, frame delay: 6900 us
14:34:31.079 -> DEBUG [94000]: Stats: 137 frames/s, frame delay: 7750 us
14:34:32.073 -> DEBUG [95000]: Stats: 123 frames/s, frame delay: 7900 us
14:34:33.067 -> DEBUG [96000]: Stats: 121 frames/s, frame delay: 7900 us
14:34:34.061 -> DEBUG [97003]: Stats: 121 frames/s, frame delay: 7900 us
14:34:35.084 -> DEBUG [98007]: Stats: 121 frames/s, frame delay: 7900 us
14:34:36.139 -> 
14:34:36.139 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
14:34:36.174 -> 
14:34:36.174 -> load 0x4010f000, len 3584, room 16 
14:34:36.174 -> tail 0
14:34:36.174 -> chksum 0xb0
14:34:36.174 -> csum 0xb0
14:34:36.174 -> v2843a5ac
14:34:36.174 -> ~ld
14:34:36.242 -> ⸮⸮
14:34:36.345 -> 
14:34:36.345 -> DEBUG [174]: Loading config
14:34:36.345 -> DEBUG [175]: 
14:34:36.345 -> System Information:
14:34:36.345 -> DEBUG [176]: Heap: 34248
14:34:36.345 -> DEBUG [176]: Boot Vers: 31
14:34:36.345 -> DEBUG [176]: CPU Speed: 80 MHz
14:34:36.345 -> DEBUG [176]: SDK: 2.2.2-dev(38a443e)
14:34:36.345 -> DEBUG [179]: Chip ID: 13955320
14:34:36.345 -> DEBUG [182]: Flash ID: 1458208
14:34:36.345 -> DEBUG [184]: Flash Size: 4194304KB
14:34:36.345 -> DEBUG [187]: Vcc: 65535
14:34:36.379 -> 
14:34:36.379 -> *WM: [1] getCoreVersion():          2_7_4
14:34:36.379 -> *WM: [1] system_get_sdk_version():  2.2.2-dev(38a443e)
14:34:36.379 -> *WM: [1] system_get_boot_version(): 31
14:34:36.379 -> *WM: [1] getFreeHeap():             32048
14:34:36.379 -> *WM: [1] AutoConnect 
14:34:36.379 -> *WM: [3] setupHostname:  newLEDs
14:34:36.413 -> *WM: [2] Setting WiFi hostname 
14:34:36.413 -> *WM: [2] Connecting as wifi client... 
14:34:36.413 -> *WM: [3] STA static IP:
14:34:36.413 -> *WM: [2] setSTAConfig static ip not set, skipping 
14:34:36.413 -> *WM: [1] Connecting to SAVED AP: ******
14:34:36.413 -> *WM: [3] Using Password: ***************
14:34:36.413 -> *WM: [3] WiFi station enable 
14:34:36.413 -> *WM: [3] enableSTA PERSISTENT ON 
14:34:36.413 -> *WM: [1] connectTimeout not set, ESP waitForConnectResult... 
14:34:39.323 -> *WM: [2] Connection result: WL_CONNECTED
14:34:39.323 -> *WM: [3] lastconxresult: WL_CONNECTED
14:34:39.323 -> *WM: [1] AutoConnect: SUCCESS 
14:34:39.323 -> *WM: [1] STA IP Address: 192.168.2.57
14:34:39.323 -> *WM: [3] hostname: STA:  newLEDs
14:34:39.323 -> INFO: Wi-Fi connected
14:34:39.323 -> DEBUG [3162]: SPIFFS contents:
14:34:39.323 -> DEBUG [3171]: FS File: /css/bootstrap.min.css, size: 121093
14:34:39.357 -> DEBUG [3171]: FS File: /css/dark-mode.css, size: 1104
14:34:39.357 -> DEBUG [3180]: FS File: /css/minicolors.min.css, size: 96597
14:34:39.357 -> DEBUG [3180]: FS File: /css/styles.css, size: 2152
14:34:39.357 -> DEBUG [3184]: FS File: /favicon.ico, size: 4286
14:34:39.357 -> DEBUG [3190]: FS File: /fonts/glyphicons.woff2, size: 18028
14:34:39.357 -> DEBUG [3194]: FS File: /images/atom196.png, size: 3889
14:34:39.357 -> DEBUG [3198]: FS File: /images/github.ico, size: 6518
14:34:39.391 -> DEBUG [3204]: FS File: /images/surr.png, size: 1897
14:34:39.391 -> DEBUG [3208]: FS File: /index.htm, size: 9599
14:34:39.391 -> DEBUG [3212]: FS File: /js/app.js, size: 16035
14:34:39.391 -> DEBUG [3219]: FS File: /js/bootstrap.min.js, size: 37045
14:34:39.391 -> DEBUG [3220]: FS File: /js/dark-mode-switch.min.js, size: 492
14:34:39.391 -> DEBUG [3230]: FS File: /js/jquery-3.1.1.min.js, size: 86709
14:34:39.391 -> DEBUG [3232]: FS File: /js/minicolors.min.js, size: 15463
14:34:39.425 -> DEBUG [3236]: FS File: /js/r-websocket.min.js, size: 3100
14:34:39.425 -> DEBUG [3241]: FS File: /settings.htm, size: 9873
14:34:39.425 -> DEBUG [3245]: FS File: /simple.htm, size: 3653
14:34:39.425 -> 
14:34:39.425 -> DEBUG [3252]: FS Size: 957314KB, used: 446529KB, 46.64%
14:34:39.425 -> 
14:34:39.425 -> DEBUG [3254]: Enabled Features:
14:34:39.425 -> DEBUG [3257]: Feature: mDNS support enabled
14:34:39.425 -> DEBUG [3261]: Feature: OTA support enabled
14:34:39.425 -> DEBUG [3265]: Feature: MQTT support enabled
14:34:39.425 -> DEBUG [3268]: Feature: UDP visualization support enabled
14:34:39.460 -> 
14:34:39.460 -> INFO: HTTP web server started
14:34:40.347 -> INFO: WiFi Connected! Open http://192.168.2.57 in your browser
14:34:40.347 -> INFO: mDNS responder started. Try to open http://newLEDs.local in your browser
14:34:40.347 -> DEBUG [4186]: Stats: 61 frames/s, frame delay: 5050 us
14:34:41.164 -> DEBUG [5003]: Stats: 148 frames/s, frame delay: 6450 us
14:34:42.154 -> DEBUG [6005]: Stats: 147 frames/s, frame delay: 7800 us
14:34:43.183 -> DEBUG [7006]: Stats: 122 frames/s, frame delay: 7900 us
14:34:44.175 -> DEBUG [8002]: Stats: 120 frames/s, frame delay: 7900 us
14:34:45.164 -> DEBUG [9001]: Stats: 120 frames/s, frame delay: 7900 us
14:34:46.155 -> DEBUG [10006]: Stats: 121 frames/s, frame delay: 7900 us
14:34:47.501 -> DEBUG [11002]: Stats: 120 frames/s, frame delay: 7900 us
14:34:48.169 -> DEBUG [12000]: Stats: 120 frames/s, frame delay: 7900 us
14:34:49.186 -> DEBUG [13005]: Heap: 27824
14:34:49.186 -> DEBUG [13006]: Stats: 121 frames/s, frame delay: 7900 us
14:34:50.172 -> DEBUG [14003]: Stats: 120 frames/s, frame delay: 7900 us
14:34:51.157 -> DEBUG [15005]: Stats: 121 frames/s, frame delay: 7900 us
14:34:52.178 -> DEBUG [16005]: Stats: 121 frames/s, frame delay: 7900 us
14:34:53.164 -> DEBUG [17000]: Stats: 120 frames/s, frame delay: 7900 us

**Comment by bb-Ricardo** [comment]
great.

@scr1ptDev: can you test it as well?

**Comment by bb-Ricardo** [comment]
Closing this issue as resolved. Thank you for testing
