### ISSUE TITLE
Request: Homey integration

### ISSUE THREAD

**Issue by MaikelKelder** [NimmLor/esp8266-fastled-iot-webserver#117]
Homey is a popular Demotica system in Europe.

Integration is described here:
https://github.com/athombv/homey-arduino-library/blob/master/docs/usage.md

I am experimenting, but as a total new guy to it, I probably not gonna make it work 100%.
If someone could help, much appreciated!

**Comment by MelloBogaarts** [comment]
Also interested in this feature, as this will make the solution more smart.

**Comment by bb-Ricardo** [comment]
Hi,

From the looks of it the basic integration would be pretty straight forward.

BUT: I personally don't have a homey device to test the integrations and actions.

Do you have an idea of how I would be able to test it without an homey device/pod?

**Comment by MaikelKelder** [comment]
The only thing I can offer is that I will try out any code you want to test?
Homey doesnt have a virtual setup or something, and the device is too costly to just buy to test ;-)
What can I do to make this easier for you?

https://github.com/athombv/com.athom.homeyduino

**Comment by MaikelKelder** [comment]
I am using in this case the Wemos D1 mini
Wifi connected (not ethernet of course)

You may need... (or I do)
Homey MAC: 2c:6b:7d:14:82:96
Homey IP: 192.168.178.216

**Comment by MaikelKelder** [comment]
I was able to register the Arduino (Wemos) to Homey by adding 3 lines lines:
(As mentioned here: https://github.com/athombv/homey-arduino-library/blob/master/docs/usage.md)
Took out the extra lines, that dont seem to be needed (wifi SSID, username and pass)

const char* name = "NanoLeafs";

void setup() {
  Homey.begin(name);
}

void loop() {
  Homey.loop();
}

With these added and builded, I can register the Arduino to the App in Homey, yet, cant control anything of course.
This is where my knowledge ends a bit, I am afraid... I dont know how to control the lights..
But so far, seems to work to get it registered on Homey atleast.

**Comment by bb-Ricardo** [comment]
Jup, this part is easy 😀.

I meant the actions to control the device is difficult to test.

Can you point me to a doku where all the actions are described? We could start with a simple switch on/off command.

**Comment by MaikelKelder** [comment]
I am looking for a more constructial guide for commands. but hope this page helps?
https://apps-sdk-v2.developer.athom.com/tutorial-App%20Development%20Guidelines.html
(Athom is the brand of Homey)

**Comment by MaikelKelder** [comment]
I Found also an example INO project on the Homey Arduino Github page:
https://github.com/athombv/homey-arduino-library/tree/master/examples/Example%20projects/Community%20projects/LedStripDriver_OpenSmart

**Comment by bb-Ricardo** [comment]
This seems to be a good source. Thank you.

On/off and brightness seems pretty forward. But I'm not sure how patterns should be controlled.

We could just simply add these two. Even though it's possible to change the color. This would make it necessary to switch to the solid color pattern.

What do you think?

**Comment by MaikelKelder** [comment]
Sounds Great, ON/OFF would already be great since it remembers it last setting.
Lets worry/experiment on the rest later :-p

Thanks for this, it greatly appreciated!

**Comment by bb-Ricardo** [comment]
I should be able to whip something up tonight.

**Comment by MaikelKelder** [comment]
*Speechless* ;-)

**Comment by bb-Ricardo** [comment]
Just did a little change. See: https://github.com/bb-Ricardo/esp8266-fastled-iot-webserver/commit/8e44930e7ccacbe00b5bb1a278cf1a7df3ffeab0

It compiles but I can't test it. Included On/Off and brightness.

Can you try it out?

**Comment by MaikelKelder** [comment]
I will! let you know ASAP!

**Comment by MaikelKelder** [comment]
Getting an error on compile, but I also get that on the original ino, now placed on in master. (6 days old)
Not getting it on the older version btw.

Error is in screenshot: "cfg was not declared
![image](https://user-images.githubusercontent.com/37801691/104388013-a2099a80-5538-11eb-84df-da9d9d6ccbd8.png)

**Comment by bb-Ricardo** [comment]
I recently changed the config management. There should be a config.h file which should be included in line 374 of that scatch. Is this file missing/empty? Or may check the end if line.

Thank you.

**Comment by MaikelKelder** [comment]
Yes, now it builds and uploads.
Homey seems to see it as a switch/dimmable device and lets me switch.
Website doesnt seem to load anymore 100%, see screenshot, tried reuploading Sketch Data, but didnt change anything.
Its 1 AM now, going to sleep. will test with leds tomorrow.
Thanks so far!!!

**PS. below is a cookie issue in Chrome, clearing cookies helped to get the webpage running normally.**
![image](https://user-images.githubusercontent.com/37801691/104390228-7dfc8800-553d-11eb-94ef-28db17fd8cef.png)

**Comment by bb-Ricardo** [comment]
Great, step by step. Did you figure out the config.h issue and why it wouldn't compile the first time?

Will add a counter later on so you can see how many loop cycles per seconds are processed. This way you can tell on the serial console if homey has a big performance impact.

**Comment by bb-Ricardo** [comment]
Just pushed another change which will display a loop/s counter in your serial console. Make sure NOT to use "glitter" als pattern, it is currently broken.

**Comment by MaikelKelder** [comment]
> Great, step by step. Did you figure out the config.h issue and why it wouldn't compile the first time?
> 
> Will add a counter later on so you can see how many loop cycles per seconds are processed. This way you can tell on the serial console if homey has a big performance impact.

I used the new master with config.h as you mentioned, my build was still without. With the config.h it builded.
I will try your newest and see if webpage also shows again..... I will do a full scrub of the WEmos.

**Comment by MaikelKelder** [comment]
Sorry, had a challenge with deleting an old device in Homey from earlier registration, as long as that existed, it didnt let me register a new one, same device, but somehow it had a conflict.
Worked that out, and whatayaknow... IT WORKS!

ON/OFF even the DIMM works! Can even put in in a flow and works!!

Serial says 116/117 loops overall, no idea whats good or bad here :-p

**Comment by bb-Ricardo** [comment]
This seems a good value. great. I could even try to add a hue setting. Are you around for some testing any longer?

**Comment by MaikelKelder** [comment]
Absolutely up for more testing

**Comment by bb-Ricardo** [comment]
Great, latest commit adds support for color setting, can you test: https://github.com/NimmLor/esp8266-fastled-iot-webserver/commit/f7feec10cf6a3fe1a3a649562c2395b34939c745

**Comment by MaikelKelder** [comment]
I do get a HUE control in Homey, but it doesnt change the color of the LEDS, they change to default white when selecting the HUE and stay white.

**Comment by bb-Ricardo** [comment]
try changing Line 1563:
`rainbowSolid();`
with
`fill_solid(leds, NUM_LEDS, CHSV(gHue, 128, 255));` or `fill_solid(leds, NUM_LEDS, CHSV(gHue, 0, 255));`

I'm just about adding saturation.

**Comment by MaikelKelder** [comment]
Getting this error on compile:


C:\Users\Maikel\Downloads\__MASTER\esp8266-fastled-iot-webserver-master\esp8266-fastled-iot-webserver\esp8266-fastled-iot-webserver.ino: In function 'void homeyLightHue()':

esp8266-fastled-iot-webserver:1563:52: error: expected primary-expression before 'or' token

  fill_solid(leds, NUM_LEDS, CHSV(gHue, 128, 255)); or fill_solid(leds, NUM_LEDS, CHSV(gHue, 0, 255));
                                                ^
exit status 1
expected primary-expression before 'or' token

**Comment by bb-Ricardo** [comment]
:D

This was meant as one of them. Try just `fill_solid(leds, NUM_LEDS, CHSV(gHue, 128, 255)); `

**Comment by MaikelKelder** [comment]
And just now I realised that :-p

Still no color change, stays white.

**Comment by bb-Ricardo** [comment]
can you change it back and add a `delay(5000);` after that line

**Comment by MaikelKelder** [comment]
Back to Rainbowsolid?

**Comment by bb-Ricardo** [comment]
Well the just to this:
```
fill_solid(leds, NUM_LEDS, CHSV(gHue, 255, 255));
delay(5000);
```

**Comment by MaikelKelder** [comment]
No change in color, but do get some LAG now in the interface of homey and sometimes timeout errors.
response before was instant, the connection seems optimal (strong wifi)

**Comment by bb-Ricardo** [comment]
Na, this was a silly idea. But i know where the issue is. Just trying to fix it properly.

**Comment by MaikelKelder** [comment]
I am hitting the sack its getting late, but again, amazing stuff, so happy this is possible and working so well.

**Comment by bb-Ricardo** [comment]
fair enough. I just pushed another commit. Let's see if this changes anything

**Comment by MaikelKelder** [comment]
No color change still, same result it seems.

**Comment by bb-Ricardo** [comment]
sorry, had another bug

pushed a new commit.

needed to set homey solid color after palette change

**Comment by MaikelKelder** [comment]
I wish I could show you the result of your work!! It WORKS!!!
I think you created in 3 days a great integration!!
Do you think its possible to integrate the Pattern selection, or is that not possible because of Homey limitations?

For other homey devices I do have a "list" option for example at my thermostat where I can select Comfort/Eco/Boost/Off for example.

**Comment by bb-Ricardo** [comment]
Awesome 👏🏼

> Do you think its possible to integrate the Pattern selection, or is that not possible because of Homey limitations?

If Homey has an API options to select a pattern, it should also be quite easy to add.

Can you go gunt for the docu again, if you can find anything? We are using the device class "light".

**Comment by MaikelKelder** [comment]
absolutely, will look for it!

**Comment by MaikelKelder** [comment]
https://apps-sdk-v2.developer.athom.com/index.html

I dont know if its of any use, this is the UI trigger:
![image](https://user-images.githubusercontent.com/37801691/104588683-0b88c680-5669-11eb-8e7f-a8011ce58fe6.png)

There is API information in this section, just dont know if its receiving or sending....
https://apps-sdk-v2.developer.athom.com/Api.html

Sorry, try to find the right information for you, just dont know enough about this stuff ;-)

**Comment by MaikelKelder** [comment]
Are Webhooks of any use? also mentioned in the same developer site.....

If none of these help, I will look somewhere else, let me know...

**Comment by bb-Ricardo** [comment]
Found this here: https://developer.athom.com/docs/apps-reference

But can't find anything matching

**Comment by bb-Ricardo** [comment]
Maybe "Next" and "Previous" seem fitting.

**Comment by MaikelKelder** [comment]
Is light_mode an option? I dont know what is the output in the UI for it... 
Seems like the picker is not available for light.

**Comment by bb-Ricardo** [comment]
Just pushed another commit. Can you test if you can change the patterns now?

**Comment by MaikelKelder** [comment]
Getting an error: (Line 13 it marks)
![image](https://user-images.githubusercontent.com/37801691/104647917-d7d28e80-56b2-11eb-9057-cb44d4fdafc9.png)

**Comment by bb-Ricardo** [comment]
Are you sure your build is clean? There have only been added a few lines and it compiled cleanly for me.

**Comment by MaikelKelder** [comment]
no idea what happend, but yeah it was me....
I compiled normal now and yes, I have a Music option now BACK and Forward, Nanoleafs respond, so it works.
No idea what I am selecting though... ;-)

If you can get this MEDIA option in there, would a "picker"also be possible from the "thermostat" capability?
Yet this list need to be filled of course, no idea how that would take place....
Ah, I think this list is very limited and not open to customization? (on/off/comfort/etc)

**Comment by bb-Ricardo** [comment]
These buttons change the pattern forth and back. These options show up as mesic options? They are defined als "speaker_next" and "speaker_prev".

Here: https://developer.athom.com/docs/apps-reference under Capabilities you can see the possible options. And "enum" is what you want. If you klick on the three dots on the right side you get the definition code. And under "enum" you can only select the predefined options.

**Comment by MaikelKelder** [comment]
Yes they work ! They just look strange in the homey ui. :-)

**Comment by bb-Ricardo** [comment]
Can we leave it like that? Then I would consider this solved and merge it to the development branch.

Or should we remove the pattern changing so it doesn't look to confusing.

**Comment by MaikelKelder** [comment]
Absolutely, thanks for your time and effort in this!! really appreciated!
For me, leave the selector in... could come in handy!

**Comment by bb-Ricardo** [comment]
Thank you. Merged it to the dev branch.
