### ISSUE TITLE
keep running loop even if power is set to off

### ISSUE THREAD

**Issue by arnaud-42** [NimmLor/esp8266-fastled-iot-webserver#127]
Hello,

I was wondering why some mornings I find my leds powered on. When a reboot happen (i don't know why it reboot yet) the leds are powered on.
Is there any way to change this default behaviour ?

**Comment by bb-Ricardo** [comment]
Hi,

you like to have the LEDs off by default at reboot?

The last power state is save and resumes after reboot.

**Comment by arnaud-42** [comment]
are you sure ?
I just tried with the led off, i unplugged it and plug it back and the light turned on.

**Comment by bb-Ricardo** [comment]
Just try out latest "in-development". Keep your serial monitor open.

It takes 10 seconds after the latest config change to save the date. Once the data is saved you sould reset the device and it should stay off.

If not, then it's a bug and I'll fix it asap.

**Comment by arnaud-42** [comment]
Thanks i'll try tommorow and report here.

**Comment by arnaud-42** [comment]
Just tried with the in-dev and it's the same, when i unplugged and plugged in back it turned ON.

Just to let you know, my esp are powered via usb.

**Comment by bb-Ricardo** [comment]
Yes, you are correct. This is a bug. Just found the problem. Will fix it later. Thanks for reporting

**Comment by bb-Ricardo** [comment]
Hi

can you test the "fix-power-off-mode" branch and see if this fixes it?

Thank you

**Comment by arnaud-42** [comment]
It's working.
Thanks.

**Comment by bb-Ricardo** [comment]
Thank you for testing. Merged to "in-development" branch
