### ISSUE TITLE
code cleanup

### ISSUE THREAD

**Issue by bb-Ricardo** [NimmLor/esp8266-fastled-iot-webserver#129]
To fix bugs and improve the code quite some cleanup should be done.

- [x] linting
- [x] order functions in groups
- [x] rename some funtions
- [x] add more debug info about device config
- [x] add more DEBUG infos

**Comment by tech-freak** [comment]
sorry for hijacking but can you please take a look in this ?

https://github.com/NimmLor/esp8266-fastled-iot-webserver/issues/113

need it for clock :/
