### ISSUE TITLE
Noob problem with the D1 Mini

### ISSUE THREAD

**Issue by MrPresident2** [NimmLor/esp8266-fastled-iot-webserver#14]
I don't want to waste any one's time, I'm pretty noob and I have a problem while trying to upload the files to the Mini D1 board. Is there anyone that is kind and would like to help me solve the problem?
You can add my discord: Mr.President#1929

**Comment by pattyland** [comment]
Advice: "a problem" is not a good or helpful description

**Comment by MrPresident2** [comment]
This is why I asked if there's someone kind enough to help me, it's too long for writing it down.

**Comment by pattyland** [comment]
I find it very impolite to discuss a problem that others may have in private.

**Comment by MrPresident2** [comment]
well, when I'm pressing tools- sketch data upload I'm getting this error:  SPIFFS Error: esptool not found!

**Comment by ghost** [comment]
I have the same mistake, I downloaded esptool with Python thinking it would fix the problem but... No. I've been trying to do this project for several months now and I still can't get to its goal because of a problem and yet I follow the instructions to the letter, it's starting to get a bit annoying >:[.

**Comment by MrPresident2** [comment]
> I have the same mistake, I downloaded esptool with Python thinking it would fix the problem but... No. I've been trying to do this project for several months now and I still can't get to its goal because of a problem and yet I follow the instructions to the letter, it's starting to get a bit annoying >:[.

Well, let's hope someone here would help us.

**Comment by ghost** [comment]
No solution to the problem?

**Comment by psu1989** [comment]
From another post: I think it is because you need the newest esptool version. Download latest release from here: https://github.com/esp8266/arduino-esp8266fs-plugin/releases
I got the same error, and I just successfully uploaded the sketch with latest version (0.5.0)
