### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by enniob** [NimmLor/esp8266-fastled-iot-webserver#141]
Will this work on ESP32?

**Comment by bb-Ricardo** [comment]
Currently not. This issue is already tracked here #77.

**Comment by bb-Ricardo** [comment]
you might wan to try the "feature-esp32-support" branch

**Comment by enniob** [comment]
Thanks, I will check it out

**Comment by bb-Ricardo** [comment]
Hey Ennio,

did you get around testing it?

I will close this issue again and keep tracking it in #77.

**Comment by enniob** [comment]
Sorry I did not. I will post here once I test.

**Comment by enniob** [comment]
I did some test last night and it looks good. I will do more testing tonight and let you know.
