### ISSUE TITLE
MQTT don't words

### ISSUE THREAD

**Issue by LordMM74** [NimmLor/esp8266-fastled-iot-webserver#149]
After activating MQTT i got following error message:

**no matching function for call to 'setSolidColor(int&, int&, int&)'**

Can anybody tell me how i can find the error?

**Comment by bb-Ricardo** [comment]
Hey, did you try the latest 'in-development' branch?

**Comment by LordMM74** [comment]
No.
I use master branch and all versions of libraries for arduino like described in Software_Installation.md.
Error also occurs if i use latest version of FastLed, PubSubClient and arduinoJson.

Should i try this branch?

**Comment by bb-Ricardo** [comment]
Yes, you should.

**Comment by LordMM74** [comment]
Thanks. Works using development branch.
