### ISSUE TITLE
simple.js is missing from in-development branch

### ISSUE THREAD

**Issue by pattyland** [NimmLor/esp8266-fastled-iot-webserver#151]
Hi,

trying out the ~~in-development~~ master branch I get the following error while loading the simple.htm:
```
Failed to load resource: the server responded with a status of 404 (Not Found) simple.js
```
It seems the simple.js is missing from the in-development branch

Greets, pattyland

**Comment by bb-Ricardo** [comment]
same as #152

**Comment by pattyland** [comment]
Sorry, I think I checked out the wrong branch... This issue is only relevant for the master branch: https://github.com/NimmLor/esp8266-fastled-iot-webserver/blob/master/data/simple.htm#L88

**Comment by bb-Ricardo** [comment]
Hi, this will be fixed as soon as the dev branch is merged to master
