### ISSUE TITLE
issue new release 4.5

### ISSUE THREAD

**Issue by bb-Ricardo** [NimmLor/esp8266-fastled-iot-webserver#153]
- [x] disable DEBUG
- [x] Check Changelog for latest changes
- [x] merge to master
- [x] tag/release

**Comment by WarDrake** [comment]
- [x] Fix MQTT topics for multiple devices

**Comment by bb-Ricardo** [comment]
Dont worry, the issue is already tagged for the milestone 🤓.

https://github.com/NimmLor/esp8266-fastled-iot-webserver/milestone/1

**Comment by bb-Ricardo** [comment]
and "4.5" is released
