### ISSUE TITLE
Nanoleaf Pattern doesn't work

### ISSUE THREAD

**Issue by Kolbaxx** [NimmLor/esp8266-fastled-iot-webserver#156]
If I'm choosing any Nanoleaf Pattern in the Webinterface the LEDs just turning off. If I choose for exampe "Color Waves" everything works fine. I got WS2812B LEDs and wired as shown in Discription

**Comment by bb-Ricardo** [comment]
did you see this issue: https://github.com/NimmLor/esp8266-fastled-iot-webserver/issues/119 ?

**Comment by Kolbaxx** [comment]
Thanks a lot didn't see this issue Post now it works perfectliy
