### ISSUE TITLE
Wemos D1 Mini does not create hotspot

### ISSUE THREAD

**Issue by Roycinger** [NimmLor/esp8266-fastled-iot-webserver#157]
Hi,
I recently downloaded the new project which is now using WiFiManager.
Unfortunately, the Wemos does not create any hotspot for me after the first initial flash.
How can I debug this?
Any help is appreciated.

edit:
Kinda strange:
Setting LED_DEBUG to 1, gave me the following output in the serial monitor:
![image](https://user-images.githubusercontent.com/7791335/107990735-5d5c9d80-6fd5-11eb-9366-5829c5da3eb6.png)
That's my WiFi that I set up months ago (without WiFiManager).
Shouldnt this be cleared? I even ran an EEPROM wipe sketch to get rid of all old data

**Comment by bb-Ricardo** [comment]
Hi,

The wifi credentials are not stored in the EEPROM.

Just add a `wifiManager.resetSettings();` somwhere in setup(), write this to your Wemos, let it reboot and then revert it again. This should delete the credentials properly.

**Comment by Roycinger** [comment]
That did the trick, thank you very much @bb-Ricardo
