### ISSUE TITLE
Nanoleaf wiring direction

### ISSUE THREAD

**Issue by Roycinger** [NimmLor/esp8266-fastled-iot-webserver#159]
Evening folks,
not really an issue, more a question on wiring the ws2812b strip.
Does it make a difference "which way round" the data line of the strip is wired?
2 pics for explain what I mean:
![image](https://user-images.githubusercontent.com/7791335/108114655-5e570300-7099-11eb-8ef9-ce862d2ded42.png)
![image](https://user-images.githubusercontent.com/7791335/108114757-821a4900-7099-11eb-9033-36a944bea6b3.png)

What I mean is:
Does the wiring direction in each leaf make a difference on how the finished leaf array behaves?
Thanks for clarifying!

**Comment by WarDrake** [comment]
Electricly speaking, no it makes no difference at all.  
visually speaking, if you wire them all the same way SOME patterns will smoother than with random directions.  

However the effect is so minimal unless you're looking for it, you won't see it.

**Comment by Roycinger** [comment]
Yes, I was speaking about the visual aspect only. Thanks for clarifying!
