### ISSUE TITLE
Wrong Web Interface

### ISSUE THREAD

**Issue by LukasVFL99** [NimmLor/esp8266-fastled-iot-webserver#160]
![image](https://user-images.githubusercontent.com/62470796/108515700-a9555e00-72c5-11eb-80f9-1b05c6481434.png)

Why does my Web Interface look like that?
I appreciate your help.

**Comment by bb-Ricardo** [comment]
Hi,

Ich weiß jetzt nicht so ganz genau was du meinst. So soll die Oberfläche aussehen.

Vermisst du was?

**Comment by LukasVFL99** [comment]
Ja den color picker und die Möglichkeit die einzelnen nanoleafs anzusteuern.

Lukas Grodotzki

**Comment by bb-Ricardo** [comment]
Das wurde angepasst. Bei vielen Pattern hatten die meisten Controls keine Wirkung. Es wurde so angepasst das man nur diejenigen angezeigt bekommt die auch wirklich unterstützt werden.

Hilft dir das weiter?

**Comment by LukasVFL99** [comment]
Also könnte es daran liegen das ich noch keine LEDs angeschlossen habe?
Ich habe das Projekt 4 ausgewählt also die nanoleafs und wollte 8 Panels
haben mit jeweils 12 LEDs.
Bis jetzt habe ich aber leider noch keine LEDs die kommen nächste Woche
erst.

**Comment by bb-Ricardo** [comment]
Dann würde das issue erst mal schließen.

Wenn weiterhin was nicht funktioniert dann kannst du gern ein neues aufmachen.
