### ISSUE TITLE
If alexa is not uncommented it still requires alexa things.

### ISSUE THREAD

**Issue by littleferris** [NimmLor/esp8266-fastled-iot-webserver#17]
I dont want to use alexa with this project but the ide is giving me a `alexa_main not declared in scope` when alexa support looks like this. ` //#define ENABLE_ALEXA_SUPPORT`. I then decided to try having it uncommented and it started giving me this error. `AlexaAutoplayEvent was not declared in this scope`.

**Comment by NimmLor** [comment]
fixed with newest commit and release
