### ISSUE TITLE
Unable to view Visualization/Patterns/Twinkles list in AudioVisualization

### ISSUE THREAD

**Issue by aceofjokers** [NimmLor/esp8266-fastled-iot-webserver#181]
Cant seem to control the board using Audio Visualization app with any of the recent versions.

![image](https://user-images.githubusercontent.com/6286590/113807613-d0012280-97a7-11eb-9006-c86d34bff6a7.png)

When "Requesting Parameters" it returns an error.
![image](https://user-images.githubusercontent.com/6286590/113807650-e1e2c580-97a7-11eb-8744-bad9e1248fd6.png)

**Comment by bb-Ricardo** [comment]
Hi,

this is better spot to report an issue: https://github.com/NimmLor/IoT-Audio-Visualization-Center

And I most likely know what's the issue here.

**Comment by aceofjokers** [comment]
Hi @bb-Ricardo,

Done!

Thanks for your help in the past too!!


Edit:
FYI - https://github.com/NimmLor/IoT-Audio-Visualization-Center/issues/12
