### ISSUE TITLE
Urls to control Lamp directly

### ISSUE THREAD

**Issue by L3-N0X** [NimmLor/esp8266-fastled-iot-webserver#183]
I really like the work, I have 5 lamps working with this code. But if I want to change the color of them, I must go on every IP adress and change the pattern. So I thought of coding an Android App, which can control all the lamps with one Button at the same time.

But to get this to work, i need a link or something similar which pushes the On and Off button automatically. Is there a way to get such a link? 

For example:  http://IP-ADRESS/power=0

If not, is there an other way to control the light without the user pushing the Button on the website?

Or how can I use the http GET and POST requests which are in the code?

**Comment by L3-N0X** [comment]
After trying a few things, I got it to work with a HTTP Request Widget using this Setup:

![Screenshot_20210411-115606](https://user-images.githubusercontent.com/76919750/114299706-106ce300-9abd-11eb-9ba9-e811f282ba31.png)
![Screenshot_20210411-115601](https://user-images.githubusercontent.com/76919750/114299707-11057980-9abd-11eb-883f-f6907b04e831.png)

**Comment by bb-Ricardo** [comment]
Great. There should be a detailed list of url params in the Readme.
