### ISSUE TITLE
Nanoleafs Freezes

### ISSUE THREAD

**Issue by raulantoine** [NimmLor/esp8266-fastled-iot-webserver#188]
My diy Nanoleafs freezes, can you help me?

Heres a video

https://youtu.be/78taMpKoS64

Thanks and sorry for my english

**Comment by WarDrake** [comment]
That looks like a reboot of the esp board, can you hook it up to a terminal and post the terminal output here please, there might be a message there saying why it keeps rebooting.

**Comment by raulantoine** [comment]
Ive changed the esp board and appears to end the problem.

Thanks for your fast response!
