### ISSUE TITLE
Help a Noob - First LED Flickering

### ISSUE THREAD

**Issue by MrPresident2** [NimmLor/esp8266-fastled-iot-webserver#194]
Hey Guys! 
This noob needs your help.
So my first LED is flickering a bit and when I turn the LEDs off through the website interface everything shut off except for the first LED that continues to blink/flicker. I changed the entire led strip and it's still happening.
Help!
Thanks :)

**Comment by WarDrake** [comment]
Can you get a log of the serial output while with debug enabled so we can help you diagnose the issue?

**Comment by MrPresident2** [comment]
> Can you get a log of the serial output while with debug enabled so we can help you diagnose the issue?

Hey Sir! 
Thank your help.
I can 100% do what you wrote up there if you woke me through the steps. As I said I'm a noob in this world and trying to learn :)

**Comment by WarDrake** [comment]
You need to set the constant called : LED_DEBUG to 1 and then upload the firmware.
then run start the arduino while it is still connected to the computer and use a terminal to look at the output and just save it and paste it here

**Comment by MrPresident2** [comment]
> You need to set the constant called : LED_DEBUG to 1 and then upload the firmware.
> then run start the arduino while it is still connected to the computer and use a terminal to look at the output and just save it and paste it here

Thank you Man!
her it is:

DEBUG [176]: Loading config

DEBUG [177]: System Information:
DEBUG [177]: Version: 4.5 (2020-02-14)
DEBUG [177]: Heap: 38656
DEBUG [177]: SDK: 2.2.2-dev(38a443e)
DEBUG [179]: Boot Vers: 6
DEBUG [181]: CPU Speed: 80 MHz
DEBUG [184]: Chip ID: 14023958
DEBUG [187]: Flash ID: 1458270
DEBUG [189]: Flash Size: 4194304KB
DEBUG [192]: Vcc: 65535
DEBUG [194]: MAC address: 50:02:91:D5:FD:16

*WM: [1] getCoreVersion():          
*WM: [1] system_get_sdk_version():  2.2.2-dev(38a443e)
*WM: [1] system_get_boot_version(): 6
*WM: [1] getFreeHeap():             36456
*WM: [1] AutoConnect 
*WM: [3] setupHostname:  LEDs
*WM: [2] Setting WiFi hostname 
*WM: [2] Connecting as wifi client... 
*WM: [3] STA static IP:
*WM: [2] setSTAConfig static ip not set, skipping 
*WM: [1] Connecting to SAVED AP: i just deleted thoseeeeeeee
*WM: [3] Using Password:  i just deleted thoseeeeeeee
*WM: [3] WiFi station enable 
*WM: [3] enableSTA PERSISTENT ON 
*WM: [1] connectTimeout not set, ESP waitForConnectResult... 
*WM: [2] Connection result: WL_CONNECTED
*WM: [3] lastconxresult: WL_CONNECTED
*WM: [1] AutoConnect: SUCCESS 
*WM: [1] STA IP Address: 192.168.1.24
*WM: [3] hostname: STA:  LEDs
INFO: Wi-Fi connected
DEBUG [1133]: SPIFFS contents:
DEBUG [1141]: FS File: /css/bootstrap.min.css, size: 121093
DEBUG [1142]: FS File: /css/dark-mode.css, size: 1350
DEBUG [1150]: FS File: /css/minicolors.min.css, size: 96597
DEBUG [1151]: FS File: /css/styles.css, size: 1392
DEBUG [1155]: FS File: /favicon.ico, size: 4286
DEBUG [1160]: FS File: /fonts/glyphicons.woff2, size: 18028
DEBUG [1165]: FS File: /images/atom196.png, size: 3889
DEBUG [1170]: FS File: /images/github.ico, size: 6518
DEBUG [1174]: FS File: /images/surr.png, size: 1897
DEBUG [1179]: FS File: /index.htm, size: 9706
DEBUG [1183]: FS File: /js/app.js, size: 16150
DEBUG [1188]: FS File: /js/bootstrap.min.js, size: 37045
DEBUG [1191]: FS File: /js/dark-mode-switch.min.js, size: 492
DEBUG [1200]: FS File: /js/jquery-3.1.1.min.js, size: 86709
DEBUG [1203]: FS File: /js/minicolors.min.js, size: 15463
DEBUG [1207]: FS File: /settings.htm, size: 10129

DEBUG [1234]: FS Size: 1953282KB, used: 438999KB, 22.47%

DEBUG [1235]: Arduino Core Version: 
DEBUG [1235]: Enabled Features:
DEBUG [1235]: Feature: mDNS support enabled

DEBUG [1237]: Configured device type: LED strip (0)
DEBUG [1242]: NUM_LEDS: 62
DEBUG [1244]: BAND_GROUPING: 1
DEBUG [1247]: PACKET_LENGTH: 62
INFO: HTTP web server started
INFO: WiFi Connected! Open http://192.168.1.24 in your browser
INFO: mDNS responder started. Try to open http://LEDs.local in your browser
DEBUG [2008]: Stats: 67 frames/s, frame delay: 5350 us
DEBUG [3000]: Stats: 129 frames/s, frame delay: 5800 us
DEBUG [4006]: Stats: 123 frames/s, frame delay: 5950 us
DEBUG [5001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [6007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [7003]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [8007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [9003]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [10008]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [11002]: Heap: 32184
DEBUG [11005]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [12009]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [13006]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [14001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [15007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [16004]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [17001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [18000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [19005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [20000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [21004]: Heap: 32160
DEBUG [21007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [22003]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [23006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [24001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [25004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [26007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [27002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [28005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [29007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [30002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [31004]: Heap: 32184
DEBUG [31007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [32002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [33006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [34001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [35004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [36007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [37003]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [38006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [39001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [40005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [41001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [41007]: Heap: 32160
DEBUG [42006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [43002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [44005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [45000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [46002]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [47007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [48002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [49005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [50008]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [51001]: Heap: 32160
DEBUG [51004]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [52007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [53001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [54004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [55007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [56002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [57005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [58000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [59003]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [60005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [61001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [61008]: Heap: 32184
DEBUG [62006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [63000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [64004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [65007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [66002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [67006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [68001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [69001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [70008]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [71002]: Heap: 31824
DEBUG [71005]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [72000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [73005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [74002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [75006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [76001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [77006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [78001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [79004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [80007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [81002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [81008]: Heap: 32184
DEBUG [82006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [83001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [84005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [85000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [86004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [87007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [88002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [89004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [90007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [91000]: Heap: 32160
DEBUG [91003]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [92007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [93002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [94005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [95000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [96004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [97008]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [98003]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [99006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [100000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [101003]: Heap: 31824
DEBUG [101006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [102001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [103004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [104007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [105002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [106005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [107000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [108003]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [109006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [110001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [111003]: Heap: 32184
DEBUG [111006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [112000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [113004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [114007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [115003]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [116006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [117001]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [118004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [119007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [120002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [121003]: Heap: 32184
DEBUG [121006]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [122002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [123005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [124000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [125004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [126008]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [127004]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [128007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [129004]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [130000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [131000]: Heap: 32184
DEBUG [131003]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [132007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [133004]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [134008]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [135004]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [136008]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [137004]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [138008]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [139003]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [140005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [141000]: Heap: 32024
DEBUG [141003]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [142007]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [143002]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [144005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [145000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [146004]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [147000]: Stats: 120 frames/s, frame delay: 5950 us
DEBUG [148003]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [149005]: Stats: 121 frames/s, frame delay: 5950 us
DEBUG [150000]: Stats: 120 frames/s, frame delay: 5950 u

**Comment by WarDrake** [comment]
There doesn't seem to be any issue with the software here, might be something with your physical device or connections, did you wire the data line of the led directly to the arduino? try adding a resistor in there if you did, or if not, maybe check if a different board does the same thing, software wise everyhing looks right

**Comment by MrPresident2** [comment]
I don't have a different board for now but I do have a few coming in in a few weeks, what kind of resistor should I use before the LED? My data line right now is connected directly to the board

**Comment by WarDrake** [comment]
It's probably noise from the data line then, anything between 100 to 1k resistor will do the trick of keeping the line clean

**Comment by MrPresident2** [comment]
> It's probably noise from the data line then, anything between 100 to 1k resistor will do the trick of keeping the line clean

Does the Watt matter? like 5w? 1/4 w?

**Comment by WarDrake** [comment]
In reality it doesn't matter at all, but I tend to work with 1/4 as those are the easiest ones to get a hold of for me.

**Comment by MrPresident2** [comment]
I just added the resistor between the data and the led but the first led is still flickering. so it didnt work

**Comment by WarDrake** [comment]
If you still have noise on the data line with a resistor there then I can only speculate there's some other hardware fault as the software is reporting no issues at all, double check your connections, your power supply and if not then try another board when you get one.

is your power connected directly to the led or is it running through the board first and then the leds? can you show your wiring diagram?

**Comment by MrPresident2** [comment]
The power connects straight to the LED, I guess ill have to wait for the new boards to come

**Comment by a-ayad** [comment]
I have also the exact same issue, I have connected a resistor and replaced the board and the problem is still there. If I try a normal code to light up the LEDs, the flickering is gone.

**Comment by jchilders99** [comment]
This is an issue with the esp8266 v3.0.0 library.  Roll back to the 2.7.4 library and the issue will go away.  I haven't opened an issue with them if someone wants to take the lead ;)

**Comment by MrPresident2** [comment]
> This is an issue with the esp8266 v3.0.0 library. Roll back to the 2.7.4 library and the issue will go away. I haven't opened an issue with them if someone wants to take the lead ;)


OMG that worked! Thanks!

**Comment by jchilders99** [comment]
> > This is an issue with the esp8266 v3.0.0 library. Roll back to the 2.7.4 library and the issue will go away. I haven't opened an issue with them if someone wants to take the lead ;)
> 
> OMG that worked! Thanks!

No problem!  It was super annoying and I swear I was getting micro flickers in the LEDs that has also gone away with 2.7.4.  I swear the animations are smoother with the older library.

**Comment by WarDrake** [comment]
Will close this Issue then, thanks for chiming in @jchilders99
