### ISSUE TITLE
First LED blinking

### ISSUE THREAD

**Issue by petjek** [NimmLor/esp8266-fastled-iot-webserver#198]
Hi there,
I just flashed a new Wemos D1 mini and have an issue with the first LED permanently bliking even when powered off. Tried two different WS2812B stripes to check if this is a hardware issue. Unfortunately both behave same. Is this perhaps because I currently only power the Wemos with via USB?
Tried newest stable as well as in-development release 

Regards,
Arne

**Comment by jchilders99** [comment]
This cropped up in another issue thread.  I found it related to the esp8266 3.0.x library and rolling back to version 2.7.4 resolved the issue.

**Comment by petjek** [comment]
Wow, thanks. What a simple fix. A hint from my latest experience: close Cura before flashing. :D
