### ISSUE TITLE
Problem with uploading the code.

### ISSUE THREAD

**Issue by MrPresident2** [NimmLor/esp8266-fastled-iot-webserver#20]
when I'm pressing tools- sketch data upload I'm getting this error: SPIFFS Error: esptool not found!

**Comment by AnthonMS** [comment]
I think it is because you need the newest esptool version. Download latest release from here: https://github.com/esp8266/arduino-esp8266fs-plugin/releases 
I got the same error, and I just successfully uploaded the sketch with latest version (0.5.0)

**Comment by MrPresident2** [comment]
That seems to solve that problem! thanks. but when I go to the serial monitor to see the IP of the esp I get nothing.

**Comment by AnthonMS** [comment]
Remember to change baud rate to 115200 the upload speed should also be set to this.
And if you had already inserted the d1 mini into the usb port, then click the small reset button on the board.

**Comment by MrPresident2** [comment]
I've changed the upload rate to 115200, but I'm not sure where is the baud rate. another question, when I write my network settings should I keep it with the "   " or delete everything and just keep the SSID name without the  " " ( example: "network" or network )

**Comment by AnthonMS** [comment]
If you mean in the Secrets.h, you need to keep the quotes. So it should look like "network".
After opening the serial monitor, it should open a small window where you can send commands. In the bottom of that window, there is a dropdown menu where you select baud rate, right next to "clear output" button.
But if you aer on wrong baud reate, it should just display gibberish characters. So try pressing the reset button on the d1 mini board, after opening serial monitor.

**Comment by MrPresident2** [comment]
Thank you for your kind help, I appreciate it.
so I've done that but I still get gibberish characters

**Comment by AnthonMS** [comment]
Hmm, weird. Are you using a Wemos D1 Mini? or another esp8266 board?

**Comment by MrPresident2** [comment]
I couldn't find Wemos D1 Mini, so I got Makerfocus D1 Mini from Amazon.

**Comment by AnthonMS** [comment]
Ok, never heard of that one before. But my suggestion is then, that you try the different baud rates there are, or google what you need for that specific board.

**Comment by MrPresident2** [comment]
Maybe do you have a link for a board that you know is good? maybe is a problem with the board I have.

**Comment by AnthonMS** [comment]
I am using this one https://www.banggood.com/D1-mini-V2_2_0-WIFI-Internet-Development-Board-Based-ESP8266-4MB-FLASH-ESP-12S-Chip-p-1143874.html?rmmds=myorder&cur_warehouse=CN
It's also a clone, but never had a problem with them.

**Comment by smoochiee** [comment]
change your esp8266 core in board manager on arduino tools tab... 0.5.0...it should work

**Comment by MrPresident2** [comment]
> change your esp8266 core in board manager on Arduino tools tab... 0.5.0...it should work

IDK what happened but I was able to upload the code before, after that I'm back to nothing working again hahaha

**Comment by MrPresident2** [comment]
> change your esp8266 core in board manager on arduino tools tab... 0.5.0...it should work

for which one of the problems?

**Comment by MrPresident2** [comment]
@AnthonMS I got new boards. I upload the code but still can't see any IP. when I go to my router I don't see any new connection there ( i could have seen the IP there if there was any connection between the board and the router). Is there any way I'm doing something wrong with the code ?

**Comment by AnthonMS** [comment]
> @AnthonMS I got new boards. I upload the code but still can't see any IP. when I go to my router I don't see any new connection there ( i could have seen the IP there if there was any connection between the board and the router). Is there any way I'm doing something wrong with the code ?

I switched to use WLED instead, because they added grouping feature. So the LEDs are grouped together. And so much nicer interface and app for Android.
