### ISSUE TITLE
WebInterface "Not Found" 

### ISSUE THREAD

**Issue by jmloudis** [NimmLor/esp8266-fastled-iot-webserver#200]
I cannot get the web interface to work. the web server is connected and working well the extension <IP address>/config.json works. Im not sure what I am doing wrong

**Comment by piedaniel** [comment]
I have the same problem. 

DEBUG [3263]: NO WEB SERVER FILES PRESENT! 

Someone have any idea?

**Comment by craigjmidwinter** [comment]
@piedaniel  - The NO WEBSERVER FILES PRESENT means that you missed step 7 on https://github.com/NimmLor/esp8266-fastled-iot-webserver/blob/master/Software_Installation.md which I think is different from what @jmloudis is seeing, which sounds like the same issue as https://github.com/NimmLor/esp8266-fastled-iot-webserver/issues/197

**Comment by bb-Ricardo** [comment]
I Assume this is a duplicate of #197. Will close this for now
