### ISSUE TITLE
LED lamp - First led flickers

### ISSUE THREAD

**Issue by DavidVelke** [NimmLor/esp8266-fastled-iot-webserver#201]
I loaded the software on my ESP around January. Recently I printed me another LED lamp. I loaded the latest version on the lamp and since the latest version the first led flickers red whether the lamp is on or off. This was not the case in the January version. Is there any way to turn off the flickering?

![RED](https://i.imgur.com/QP6LJvj.jpeg)

**Comment by WarDrake** [comment]
The issue is the FastLED library, there's serveral issues dealing with this already, just downgrade the library to a version 2 instead of 3 and the issue goes away when you recompile.
