### ISSUE TITLE
Web Interface not found

### ISSUE THREAD

**Issue by JustinHenryLo** [NimmLor/esp8266-fastled-iot-webserver#203]
Hello, I have a question about the web interface, is it supposed to be empty because the project is moving towards the C# interface? Or is there something missing in my set up thats why the page is just "Not Found"?

**Comment by WarDrake** [comment]
Once you enter any data into the config in the AP, regardless of it is correct or not, a config file is created and the AP is not started anymore, what you need to do is DELETE ALL FLASH DATA not just upload the files again, once you delete the flash data AND uploads the files again, an AP will be generated again.

**Comment by JustinHenryLo** [comment]
Im sorry I misunderstood my problem, I thought I misinputted the credentials in AP, because the endpoint I was expecting didn't show a webpage with LED controls. But my credentials were correct all along. The Interface was really just showing not found because when I tried using postman to alter the patterns, they just worked fine. Is there a misstep in my configuration?
