### ISSUE TITLE
Very Slow UDP (1 fps)

### ISSUE THREAD

**Issue by CastleSeven** [NimmLor/esp8266-fastled-iot-webserver#204]
I'm trying to use the IoT-Audio-Visualizer project to send spectrum data from my PC over UDP to the Wemos D1 Mini. I've verified using wireshark that plenty of packets are being sent to the LED controllers IP via UDP, so I started looking into the Wemos side of things. 

Using some bracketed timing, it looks like (at least for NanoleafWaves, but likely all the other visualizers as I'm experiencing the same behavior for all visualizer patterns) the parseUdp() call + the ShiftLeds call is taking a full second of time (resulting in ~ 1fps speeds).

![image](https://user-images.githubusercontent.com/965241/134447873-e60d3306-c3aa-4cd7-8888-b9bf5e81224a.png)

I'll do some more digging on my end to see if 

a) ShiftLeds could be the culprit (not likely given a first pass look)
b) There's a specific portion of parseUdp() that's blocking and if there's a way around it.

**Comment by CastleSeven** [comment]
Unfortunately it looks like Udp.ReadBytes() is the culprit:

![image](https://user-images.githubusercontent.com/965241/134448855-cf36704c-f8be-4d1a-a8c8-138dff17136b.png)

**Comment by CastleSeven** [comment]
OK, well, I have no idea why but I managed to get it working. After being unable to find a specific reference for "readBytes" in the Arduino UDP Library, I changed readBytes to simply 'read' and the speed is fast enough to nearly keep up now. 

![image](https://user-images.githubusercontent.com/965241/134449985-99d0c335-b97a-49fb-89a0-732091e6d9b0.png)

I'll try to fork and submit a pull request tomorrow, just in case anyone was excited to use their visualizer tonight this may help :)

**Comment by WarDrake** [comment]
Hadn't tried it in a while, but you're right, it's taking up to a second to switch frames, please assign me when you make the PR so I can test it

**Comment by WarDrake** [comment]
The change to read from readBytes restored the animations to a proper speed.
