### ISSUE TITLE
First LED flickering - WS2812B

### ISSUE THREAD

**Issue by sadikozel** [NimmLor/esp8266-fastled-iot-webserver#207]
Hello,
My first LED flickering even though I turn the LEDs off. So far I have tried;
>Putting resistor between data output and LED
>Including #define FASTLED_INTERRUPT_RETRY_COUNT 0
>Roll back to the version 2.7.4 on esp8266 library

When I roll back to old version on esp8266 library it stops flickering but it stucks on last colors and I can't change them somehow. Do you have any suggestions?

**Comment by WarDrake** [comment]
This has been brought up in the issues multiple times now, a quick search is great for getting answers.

Downgrade the FastLED library to any version 2, version 3 causes this isse.
