### ISSUE TITLE
Problem when I upload the code

### ISSUE THREAD

**Issue by ghost** [NimmLor/esp8266-fastled-iot-webserver#21]
I have this problem and I don't know how to fix it : 
`esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

SPIFFS Upload failed!`

**Comment by smoochiee** [comment]
change your esp8266 core t0 5.0

**Comment by ghost** [comment]
Already have 0.5.0

**Comment by smoochiee** [comment]
still not working?u have add spiff on your document?

**Comment by ghost** [comment]
Which document?

**Comment by smoochiee** [comment]
document/arduino/tools/

**Comment by smoochiee** [comment]
if problem not fixed maybe you have bad d1 mini. ..you error show that module is not responding or connected

**Comment by ghost** [comment]
I'll look at it when I get home. For the arduino, I just got the same one I got from Thingiverse.

**Comment by ghost** [comment]
Okay, so I think it's just the card that sucks because I did everything right and put them all in the right folders.
![image](https://user-images.githubusercontent.com/58150318/75157386-4b268700-5714-11ea-946c-7631554a3da4.png)

**Comment by NimmLor** [comment]
Hi, you might have wrong upload settings. Please verify that the upload settings look the same as in the screenshot below (except for the port).

![](https://github.com/NimmLor/esp8266-fastled-webserver-alexa/blob/master/software_screenshots/upload_settings.png?raw=true)

**Comment by ghost** [comment]
What the... Okay... I plugged in USB 2.0 on my motherboard and successfully uploaded.

**Comment by ghost** [comment]
Ah, and I reinstalled the driver.

**Comment by ghost** [comment]
So, now the problem is that I can't find the ESP on my network and when I click on the "reset" button with the serial monitor no IP address is displayed (I soldered the leds and they are white and when I click on "reset" I feel like they blink for a millisecond).

**Comment by MrPresident2** [comment]
I have the same problem, I uploaded the code, but nothing happens and I can't see the IP or the board on my wifi.  did you solve that problem?
