### ISSUE TITLE
[Help] blink first led

### ISSUE THREAD

**Issue by cdiprete** [NimmLor/esp8266-fastled-iot-webserver#218]
Hi, 
I have realized the project nanoleaf (9 triangles with 12 led for triangle) with nodemcu v3, the code is ok, but the first led on the strip led blink always, why?
 How can I modify the code for eliminate the problem?

**Comment by WarDrake** [comment]
Thre's plenty of issues already files with this, downgrade you FastLED library to something under version 3.
