### ISSUE TITLE
Board isn't connecting to WiFi/can't fine IP

### ISSUE THREAD

**Issue by MrPresident2** [NimmLor/esp8266-fastled-iot-webserver#23]
Hey Guys,
after uploading the code it seems like nothing really happens. I can't find the IP address and when I look at my network I can't see any new devices at all.
I hope you guys can help me with that.
Thanks!

**Comment by NimmLor** [comment]
Hi, have you tried connecting via the serial monitor to the esp8266?
Upon reset the terminal should print the IP.

**Comment by MrPresident2** [comment]
Yeah, I did, but again nothing is showing up and it seems like the board is not connecting to my network otherwise I could have seen it at my router settings but there's no new connection there.
