### ISSUE TITLE
Board isn't connecting to WiFi/can't fine IP 

### ISSUE THREAD

**Issue by MrPresident2** [NimmLor/esp8266-fastled-iot-webserver#26]
Hey Guys,
after uploading the code it seems like nothing really happens. I can't find the IP address and when I look at my network I can't see any new devices at all.
I hope you guys can help me with that.
Thanks!

**Comment by visualdeath** [comment]
You are not really giving us much information to try and help you with your issue. Can you send a serial monitor log. Have you verified the WiFi settings in your secrets.h file?

**Comment by MrPresident2** [comment]
Yes, my wifi settings are correct, and I'm getting nothing on my serial monitor that's the problem.
I've been trying to do this project for the last 3 months IDK what to do and I really need someones to help

**Comment by visualdeath** [comment]
You are not getting any output on the serial monitor? Is the serial monitor set on 115200 baud? What kind of board are you uploading to?

**Comment by MrPresident2** [comment]
It is set on that, and I tried all the other baud options. It's a mini D.
If you have discord or something we can talk so it will be easier ill pay you for your time.

**Comment by visualdeath** [comment]
https://discord.gg/7nJbE5
