### ISSUE TITLE
Change triangle number from webpage

### ISSUE THREAD

**Issue by 1975felix** [NimmLor/esp8266-fastled-iot-webserver#33]
Is possible to change number of installed triangle from the webpage, without re-compiling and send sketch?
Thankyou

**Comment by NimmLor** [comment]
No, it's not possible, adding this in could introduce many new problems. In the next update there will be OTA support, so the esp8266 can be flashed without connecting it via usb to the pc.

**Comment by NimmLor** [comment]
New update is here, OTA is now implemented.

**Comment by 1975felix** [comment]
Wow, fantastic thank you very good job
