### ISSUE TITLE
[Suggestion] Visualizer modes

### ISSUE THREAD

**Issue by flashez** [NimmLor/esp8266-fastled-iot-webserver#39]
New audio visualization is really nice.
I love the mode "41 - Nanoleaf Rainbow Band Visualizer" but the use of a threshold might be a good idea to avoid less bright triangles.
It reacts well but by default triangles are slightly on and looks not that great.
For exemple, you set a threshold to a value higher than default. When it reaches above, the triangle can light up.

Video of "less bright" triangles : https://www.youtube.com/watch?v=GOeTbD6uXnM

**Comment by NimmLor** [comment]
Might be implemented into the next update

**Comment by NimmLor** [comment]
Reduced threshold to 0 in [Release 4.1](https://github.com/NimmLor/esp8266-fastled-iot-webserver/releases/tag/4.1)

**Comment by flashez** [comment]
Didn't see any changes with mode "Nanoleaf Rainbow Band Visualizer"

EDIT: In fact now when there is no audio source it's now completely off, great.

**Comment by flashez** [comment]
I tried to change value to negative and it's working flawlessly !
![Capture](https://user-images.githubusercontent.com/32676706/84952724-ba285100-b0f2-11ea-85f1-32b28afcfcf9.PNG)
