### ISSUE TITLE
between patterns it flash short to white (flash)

### ISSUE THREAD

**Issue by hexxter** [NimmLor/esp8266-fastled-iot-webserver#47]
HW: MCU Wemos Mini without level converter (but i see no artifacts i think this ist not the problem)
it flash if it change the pattern its not good to see if the brightness is high but with low brightness. I will use it as night lamp for my childs but if its flash i can it not use.
The problem can be a reset or something im not sure if its the end of an pattern and a new start or it hangs and resets with an flash...

br Hexxter

**Comment by MaxHuerlimann** [comment]
I am getting the same problem, using the wemos d1 mini pro. Also not using a level converter without seeing any artifacts. Running just 24 ws2812b leds

**Comment by NimmLor** [comment]
I haven't figured out yet why the wemos crashes but removing the following line from the code should fix it:

`#define FASTLED_ALLOW_INTERRUPTS 0`

**Comment by bb-Ricardo** [comment]
Closing this issue due to no response. If you still having troubles consider opening a new issue.
