### ISSUE TITLE
First leaf randomly flickers when off

### ISSUE THREAD

**Issue by flashez** [NimmLor/esp8266-fastled-iot-webserver#53]
When my nanoleafs are off, the first leaf randomly turns on for a fraction of a second (blue color) for no reason. I would say it happens roughly every 5 minutes.
This wasn't happening with the old firmware (https://github.com/NimmLor/esp8266-nanoleaf-webserver).

**Comment by WarDrake** [comment]
That means You've likely have a reboot issue, as booting will cause that, connect it to a serial monitor and keep a look on it for an hour or so, the error there should help diagnose why it's rebooting.

**Comment by flashez** [comment]
> That means You've likely have a reboot issue, as booting will cause that, connect it to a serial monitor and keep a look on it for an hour or so, the error there should help diagnose why it's rebooting.

Updated to today's update, will see.

**Comment by ZeppDK** [comment]
damit, i have the same issue after updating nanoleaf to the latest version... 
i'll see if i can get a log enough cable to hook it up over some time :)

**Comment by ZeppDK** [comment]
what baudrate shout it have?
im getting nonsens right now, and it looks like when connecting to a router with the wrong baud rate...

**Comment by ZeppDK** [comment]
nevermind... got it working at 115200...
collecting data :)

**Comment by ZeppDK** [comment]
[nanoleaf_crash.txt](https://github.com/NimmLor/esp8266-fastled-iot-webserver/files/4880258/nanoleaf_crash.txt)

there is not alot of data when its crashing, but maybee you can use this to something @WarDrake

**Comment by WarDrake** [comment]
are you using a weemos D1 or a nodeMCU?
or some other board?

**Comment by ZeppDK** [comment]
WeMos D1 Mini

**Comment by WarDrake** [comment]
try applying this patch :
https://github.com/WarDrake/esp8266-nanoleaf-webserver/commit/e3e5124d1d7de959cfe474fa6ecfa506c967b5a3

**Comment by ZeppDK** [comment]
with that mod, it has been running for 2 hours without rebooting, so it seems to have fixed the error.

**Comment by bb-Ricardo** [comment]
Closing this issue. Please reopen if the issue persists.
