### ISSUE TITLE
[HELP] Led Max per "Leaf"

### ISSUE THREAD

**Issue by dfletch642** [NimmLor/esp8266-fastled-iot-webserver#58]
Is there a hidden 25 LED lax per leaf/panel? My panels have 29 LEDs and for several of the effects the last 4 LEDs will not be used. Is there anyway to get around this?

**Comment by WarDrake** [comment]
no hidden max, but the math of the effects assumes they are multiples of 3 as there's 3 corners, so I'm sure your 29 breaks the math on several of them and that's why it does that.

**Comment by bb-Ricardo** [comment]
has your issue been resolved?

**Comment by bb-Ricardo** [comment]
Closing this issue due to no response. If you still having troubles consider opening a new issue.
