### ISSUE TITLE
[HELP] the code have something bad?

### ISSUE THREAD

**Issue by Guspin** [NimmLor/esp8266-fastled-iot-webserver#63]
The "setSolidColor(d->getR(), d->getG(), d->getB());" which is on line 3611 is sending compilation errors.
Here is the error that sends:
https://pastebin.com/vtcuVQPb

I checked the versions of the libraries and nothing is wrong
If someone knows whats the error please help me :(

**Comment by NimmLor** [comment]
Hi, I've noticed that issue too, it is caused by a recent merge request. It should be fixed in the [in-development branch](https://github.com/NimmLor/esp8266-fastled-iot-webserver/tree/in-development). Clone the code from there and try again.

Sorry for the inconvenience.

**Comment by Guspin** [comment]
Thanks for answering!

**Comment by Guspin** [comment]
Thanks for answering! 
I spend some hours reading the code, and found out that what it fixed was "setSolidColor(d->getR(), d->getG(), d->getB(), **true**);"   that "true" was a few lines down of where the issue was happening it works on the in-dev code and the normal one, at least it compiles, I haven't try it yet to put it on to the board.

Also, the in-dev code has an issue when selecting type 4 device, it says that "BAND_GROUPING" doesn't exist, it is fixed by, well, adding that, it is not the best solution.

PD: this project is awesome! I hope that in a future I could donate some money for doing this!

**Comment by kerta1n** [comment]
Hi, I have the same issue even after downloading from the in-dev fork. Here are the errors from the IDE: pastebin.com/Er3qwiXf

**Comment by bb-Ricardo** [comment]
Can you try out the current master branch? It should be fixed by now.

**Comment by bb-Ricardo** [comment]
Closing this issue due to no response. If you still having troubles consider opening a new issue.
