### ISSUE TITLE
Alexa doesn't find the ESP

### ISSUE THREAD

**Issue by Roycinger** [NimmLor/esp8266-fastled-iot-webserver#65]
Hi,
I enabled Alexa Support by uncommenting #define ENABLE_ALEXA_SUPPORT and uncommented #define AddAutoplayDevice (...).
I also installed the needed library.
Using the WebUI, I navigate to the "Alexa Pairing" tab which gives me a new screen, telling me to search for devices.
I'm using the Alexa app on my iPhone for that (ESP + Phone are in the same WiFi).
However, the Alexa app doesn't find any new devices. 

I went through the code but honestly, I don't find a starting point to debug this issue. 
Is a physical Echo device or any specific skill needed for this?

Any help is appreciated.

Additional information:

- Similar issue is described in the espalexa git issue section:
https://github.com/Aircoookie/Espalexa/issues/120
- Also a downgrade of the ESPAlexa lib to 2.4.4 didnt work

**Comment by NimmLor** [comment]
Is your Echo device located in the same network as the esp?
What echo device and which generation of it are you using.

You can add `#define ESPALEXA_DEBUG` before `#include <Espalexa.h>` to get information in the serial monitor when attempting to pair the device.

**Comment by Roycinger** [comment]
Yes, I'm tried the iPhone app and the browser to discover from within the same Wifi. 
There's no physical Echo device present at this time.
I already tried adding ESPALEXA_DEBUG, I couldnt find anything special in the output.
There were UDP requests from a few devices but nothing the Wemos did respond to.

**Comment by NimmLor** [comment]
Unfortunatly the library states: 

> Espalexa only works with a genuine Echo speaker, it probably wont work with Echo emulators, RPi homebrew devices or just the standalone app.

I don't think that I can do anything for you :(

**Comment by Roycinger** [comment]
I read that in the lib description after creating the issue, too :)
I'll close the issue for now and order a 3rd gen Echo to test it

**Comment by emersonsc** [comment]
> I read that in the lib description after creating the issue, too :) I'll close the issue for now and order a 3rd gen Echo to test it

Any luck? My echo doesnt find mine either

**Comment by Roycinger** [comment]
> > I read that in the lib description after creating the issue, too :) I'll close the issue for now and order a 3rd gen Echo to test it
> 
> Any luck? My echo doesnt find mine either

With the 3rd Gen Echo, I got it to work.
I'm facing another issue with the sketch but the creator seems not to answer issues unfortunately
