### ISSUE TITLE
Type #5 has errors

### ISSUE THREAD

**Issue by iammenotyou** [NimmLor/esp8266-fastled-iot-webserver#73]
When trying to use the logo (type 5) it has errors preventing compiling.

resolution:
I found Line 341: 
`#elif VISUALIZER_TYPE == 5`

should be changed to:
`#elif DEVICE_TYPE == 5`

This should resolve the issue of "banding" and "num_leds" being missing.

**Comment by bb-Ricardo** [comment]
@NimmLor If have the same issue but don't really know how to fix it.

**Comment by bb-Ricardo** [comment]
Fixed in latest "in-development" branch. will close this issue for now.

Fell free to reopen this issue if it still persists.
