### ISSUE TITLE
user_interface.h: No such file or directory

### ISSUE THREAD

**Issue by wedgevic** [NimmLor/esp8266-fastled-iot-webserver#75]
It seems that that file is not there, no matter what I do, I tried reinstalling it, I tried different sources, nothing.

**Comment by wedgevic** [comment]
![image](https://user-images.githubusercontent.com/53971909/95623181-74451f00-0a3a-11eb-8af9-39711ec15d9f.png)

**Comment by WarDrake** [comment]
Select the proper esp8266 board, you're trying to compile for an arduino uno that's why you get that error.

**Comment by wedgevic** [comment]
thank you

**Comment by wedgevic** [comment]
it worked but now it says this:
![image](https://user-images.githubusercontent.com/53971909/95773731-a77aee80-0c84-11eb-8119-02e61cb369d0.png)

**Comment by wedgevic** [comment]
yay.
