### ISSUE TITLE
Various errors when compiling the sketch

### ISSUE THREAD

**Issue by elcoyotex** [NimmLor/esp8266-fastled-iot-webserver#81]
Hello Goodnight!!
I'm trying to compile and upload the sketch but it gives me these errors, I have followed all the steps in the guide and I don't know what it might be due to.
Thanks and best regards!

Arduino:1.8.12 (Windows 10), Tarjeta:"LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:1MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

In file included from C:\Users\bora_\Desktop\esp8266-fastled-iot-webserver\esp8266-fastled-iot-webserver.ino:20:0:

C:\Users\bora_\Documents\Arduino\libraries\FastLED/FastLED.h:14:21: note: #pragma message: FastLED version 3.003.002

 -#    pragma message "FastLED version 3.003.002"

In file included from C:\Users\bora_\Documents\Arduino\libraries\FastLED/FastLED.h:65:0,

from C:\Users\bora_\Desktop\esp8266-fastled-iot-webserver\esp8266-fastled-iot-webserver.ino:20:

C:\Users\bora_\Documents\Arduino\libraries\FastLED/fastspi.h:130:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 -#      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

C:\Users\bora_\Desktop\esp8266-fastled-iot-webserver\esp8266-fastled-iot-webserver.ino: In lambda function:

esp8266-fastled-iot-webserver:1018:9: error: 'switchedTimePattern' was not declared in this scope

 switchedTimePattern = true;

Usando librería FastLED con versión 3.3.2 en la carpeta: C:\Users\bora_\Documents\Arduino\libraries\FastLED 
Usando librería ESP8266WiFi con versión 1.0 en la carpeta: C:\Users\bora_\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.0\libraries\ESP8266WiFi 
Usando librería ESP8266WebServer con versión 1.0 en la carpeta: C:\Users\bora_\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.0\libraries\ESP8266WebServer 
Usando librería EEPROM con versión 1.0 en la carpeta: C:\Users\bora_\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.0\libraries\EEPROM 
Usando librería ESP8266mDNS con versión 1.2 en la carpeta: C:\Users\bora_\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.0\libraries\ESP8266mDNS 
exit status 1
'switchedTimePattern' was not declared in this scope

**Comment by NimmLor** [comment]
Noticed that issue too a few hours ago. Should be fixed in my latest commit.
