### ISSUE TITLE
Suggestion: Razer Chroma Support

### ISSUE THREAD

**Issue by OmegaRogue** [NimmLor/esp8266-fastled-iot-webserver#84]
It would be nice if this had Razer Chroma support to sync everything with other Razer Chroma enabled hardware and use Razer Chroma Apps with it

**Comment by WarDrake** [comment]
I like the Idea, I think I'm gonna add it if Nim doesn't want to do it himself.

**Comment by NimmLor** [comment]
Unfortunately I do not have a single Razer device 😅

**Comment by WarDrake** [comment]
Alright, I'll take on this then.

**Comment by WarDrake** [comment]
After multiple attempts to subscribe to Razer's Chroma API development program there's still no response from them

I'll be closing this and visiting it back if I find a way to get access to their API documentation.

**Comment by bb-Ricardo** [comment]
I also tried looking into it. Seems a lot of trouble to implement.
