### ISSUE TITLE
WiFi Manager implementation

### ISSUE THREAD

**Issue by Joachim82** [NimmLor/esp8266-fastled-iot-webserver#85]
Hello, 
Could you please implement the WiFi Manager ?
Thanks and kind regards

**Comment by charitha95** [comment]
Greate feature. Would love to see this coming :)

**Comment by bb-Ricardo** [comment]
It is already implemented here:
https://github.com/jasoncoon/esp8266-fastled-webserver/commit/473e97db327b37ff8a20cd3ab9181fc2043022e0
https://github.com/jasoncoon/esp8266-fastled-webserver/commit/e4747794323a2c43e2f84c1fdf2dabe98ed8f552

this made it really easy to set up

**Comment by NimmLor** [comment]
Implemented in [Release 4.4](https://github.com/NimmLor/esp8266-fastled-iot-webserver/releases/tag/4.4)

**Comment by bb-Ricardo** [comment]
Awesome. Thank you.
