### ISSUE TITLE
Web UI unresponsive after use of Visualizer 

### ISSUE THREAD

**Issue by Birdup** [NimmLor/esp8266-fastled-iot-webserver#87]
When IoT-Audio-Visualization-Center is used, the web interface can become unresponsive. It is unclear what resolves the issue, however flashing the board does not. It seems that some connection is being help/hung from the client.

**Comment by bb-Ricardo** [comment]
Can you try the "in-development" branch and set `LED_DEBUG` to `1`? can you post the serial monitor output here?

**Comment by bb-Ricardo** [comment]
Closing this issue due to no response. If you still having troubles consider opening a new issue.
