### ISSUE TITLE
problems with alexa configuration

### ISSUE THREAD

**Issue by Mastro860** [NimmLor/esp8266-fastled-iot-webserver#88]
I am creating the nanoleaf and modifying the arduino code I saw that it is different from how the instructions show for example there is no volts variable but only the amps variable but the biggest problem I am having is that even if I added the espalexa library in the code the variable ENABLE_ALEXA_SUPPORT does not appear
Can you help me solve the problem thanks

**Comment by bb-Ricardo** [comment]
you have to uncomment it. See: #89

**Comment by bb-Ricardo** [comment]
Closing this issue due to no response. If you still having troubles consider opening a new issue.
