### ISSUE TITLE
my led light is glitching and i want to change the strip too!

### ISSUE THREAD

**Issue by ranap040** [NimmLor/esp8266-fastled-iot-webserver#9]
Hello it seems to be working but my rgb strip is glitching and every time 3 or more led litted up than the no. of led shuld be litted according to the code also i am thinking to upgrade my rgb strip with 4 in 1 rgb strip( each led packed with one red,blue,green and a white/warm white light) will this code work for it or does need to change the code!
plz guide!
as a power supply i am using a 5v-5amp adapter.

**Comment by NimmLor** [comment]
Yes the code works with SK6812 Led-Strips whichs is a RGBW strip. Just change LED_TYPE to SK6812.
