### ISSUE TITLE
Web UI only says "Not found: /"

### ISSUE THREAD

**Issue by paulblum00** [NimmLor/esp8266-fastled-iot-webserver#90]
I did everything as described, the console gives me a local IP but when I enter it in my browser it only says "Not found: /"

**Comment by paulblum00** [comment]
nvm missed a step in the instructions

**Comment by claudiudaba** [comment]
Hei, what step did you missed ? I have the same problem.

**Comment by paulblum00** [comment]
> Hei, what step did you missed ? I have the same problem.

Step 3.2, after uploading the code
