### ISSUE TITLE
error compiling  when i work with mqtt ????

### ISSUE THREAD

**Issue by rompipelotas** [NimmLor/esp8266-fastled-iot-webserver#97]
[
![error compiling](https://user-images.githubusercontent.com/16278202/102192588-44434d80-3ebb-11eb-8858-8b7e824498d7.JPG)
](url)

**Comment by rompipelotas** [comment]
every thing ok !!!           
Modificata la riga in "setSolidColor (cr, cg, cb, false);"
thanks!!!!

**Comment by ingopmeyer** [comment]
Hi, I have the same error now. What have you done to resolve it??

Thanks,
~Ingo

**Comment by bb-Ricardo** [comment]
did you try the newest master branch? The problem should be fixed now.

**Comment by bb-Ricardo** [comment]
This has been fixed in current "in-development" branch
