### ISSUE TITLE
problema wifiappsk

### ISSUE THREAD

**Issue by Mastro860** [NimmLor/esp8266-fastled-iot-webserver#99]
![2020-12-17](https://user-images.githubusercontent.com/75782511/102538582-c050b780-40ac-11eb-94d5-b58c8c0c6cdc.png)

**When I try to download the code on the card I get this error, can someone help me please.**

**Comment by NimmLor** [comment]
You are using an old version of the software, please download the latest version from the releases.

https://github.com/NimmLor/esp8266-fastled-iot-webserver/releases
